//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordFiller.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WordFiller.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap about_default {
            get {
                object obj = ResourceManager.GetObject("about_default", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap about_hover {
            get {
                object obj = ResourceManager.GetObject("about_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap checkanswers_default {
            get {
                object obj = ResourceManager.GetObject("checkanswers_default", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap checkanswers_hover {
            get {
                object obj = ResourceManager.GetObject("checkanswers_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap checkboard {
            get {
                object obj = ResourceManager.GetObject("checkboard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap checkboard_hover {
            get {
                object obj = ResourceManager.GetObject("checkboard_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap clear_default {
            get {
                object obj = ResourceManager.GetObject("clear_default", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap clear_hover {
            get {
                object obj = ResourceManager.GetObject("clear_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap deletebutton {
            get {
                object obj = ResourceManager.GetObject("deletebutton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re currently editing a resource, you need to finish with that first....
        /// </summary>
        internal static string Editing_Resource_Message {
            get {
                return ResourceManager.GetString("Editing_Resource_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold Up....
        /// </summary>
        internal static string Editing_Resource_Title {
            get {
                return ResourceManager.GetString("Editing_Resource_Title", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap eliseboyd {
            get {
                object obj = ResourceManager.GetObject("eliseboyd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap exit_default {
            get {
                object obj = ResourceManager.GetObject("exit_default", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap exit_default_small {
            get {
                object obj = ResourceManager.GetObject("exit_default_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap exit_hover {
            get {
                object obj = ResourceManager.GetObject("exit_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap exit_hover_small {
            get {
                object obj = ResourceManager.GetObject("exit_hover_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hand_default {
            get {
                object obj = ResourceManager.GetObject("hand_default", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hand_grab {
            get {
                object obj = ResourceManager.GetObject("hand_grab", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hand_left {
            get {
                object obj = ResourceManager.GetObject("hand_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hand_right {
            get {
                object obj = ResourceManager.GetObject("hand_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap header_default {
            get {
                object obj = ResourceManager.GetObject("header_default", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap header_main {
            get {
                object obj = ResourceManager.GetObject("header_main", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap header_terminator {
            get {
                object obj = ResourceManager.GetObject("header_terminator", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap library_default {
            get {
                object obj = ResourceManager.GetObject("library_default", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap library_hover {
            get {
                object obj = ResourceManager.GetObject("library_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap logo_small {
            get {
                object obj = ResourceManager.GetObject("logo_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lucasmoffitt {
            get {
                object obj = ResourceManager.GetObject("lucasmoffitt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_down_default {
            get {
                object obj = ResourceManager.GetObject("menu_down_default", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_down_hover {
            get {
                object obj = ResourceManager.GetObject("menu_down_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_up_default {
            get {
                object obj = ResourceManager.GetObject("menu_up_default", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_up_hover {
            get {
                object obj = ResourceManager.GetObject("menu_up_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap microsoft_kinect {
            get {
                object obj = ResourceManager.GetObject("microsoft-kinect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap newbutton {
            get {
                object obj = ResourceManager.GetObject("newbutton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to select a resource before you can open it..
        /// </summary>
        internal static string No_Resource_Selected_Content {
            get {
                return ResourceManager.GetString("No_Resource_Selected_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a resource.
        /// </summary>
        internal static string No_Resource_Selected_Title {
            get {
                return ResourceManager.GetString("No_Resource_Selected_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to enter a title before you can save your resource....
        /// </summary>
        internal static string Null_Resource_Title_Content {
            get {
                return ResourceManager.GetString("Null_Resource_Title_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a resource title....
        /// </summary>
        internal static string Null_Resource_Title_Title {
            get {
                return ResourceManager.GetString("Null_Resource_Title_Title", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap openresource {
            get {
                object obj = ResourceManager.GetObject("openresource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap savebutton {
            get {
                object obj = ResourceManager.GetObject("savebutton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap settings_default {
            get {
                object obj = ResourceManager.GetObject("settings_default", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap settings_hover {
            get {
                object obj = ResourceManager.GetObject("settings_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
